// import { urlFor } from '$lib/utils/image';

// export async function GET() {
//   // Fetch works from the sanity utility
//   const works = await getWorks();

//   // Create XML for individual work pages with their corresponding images
//   const worksSlugsXML = works.map(work => {
//     return `
//       <url>
//         <loc>https://www.lucabunino.com/work/${work.slug.current}</loc>
//         <lastmod>${work.year}</lastmod>
//         <priority>0.80</priority>
//         <image:image>
//           <image:loc>${urlFor(work.thumbnail).url()}</image:loc>
//         </image:image>
//       </url>`;
//   }).join('');

//   // Build the complete sitemap
//   return new Response(
//     `
//     <?xml version="1.0" encoding="UTF-8"?>
//     <urlset
//           xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
//           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
//           xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
//                 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
//     <url>
//       <loc>https://www.europan.ch/</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>1.00</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/concours</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/concours/sujet</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/concours/deroulement</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/a-propos</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/a-propos/qu-est-ce-qu-europan</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/a-propos/equipe</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/a-propos/partenaires</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/a-propos/soutenez-nous</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/news</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/contact</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.80</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e16-ville-vivantes-1</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e14-productive-cities</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e13-la-ville-adaptable-2</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e12-la-ville-adaptable</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e11-territoires-et-modes-de-vie-en-resonances</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e10-urbanite-europeenne-inventer-l-urbanite</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e9-urbanite-europeenne-ville-durable-et-nouveaux-espaces-publics</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e7-challenge-suburbain-intensites-et-diversites-residentielles</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e6-entre-villes</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e5-les-nouveaux-paysages-de-l-habitat</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e4-entre-villes-dynamiques-architecturales-et-urbanite-nouvelle</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e2-habiter-la-ville</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/archive/e1-evolution-des-modes-de-vie-et-architecture-du-logement</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/news/nous-avons-un-nouveau-site-web</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/news/forum-europan-inter-sessions-E17-E18</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>
//     <url>
//       <loc>https://www.europan.ch/news/rendez-vous-de-l-urbanisme-2024</loc>
//       <lastmod>2025-02-14T09:45:47+00:00</lastmod>
//       <priority>0.64</priority>
//     </url>

//     </urlset>
//     `.trim(),
//     {
//       headers: {
//         'Content-Type': 'application/xml'
//       }
//     }
//   );
// }
